# Precept 1 (Intro to git) Rubric:
* +50 for accepting the assignment and creating a repository
* +15 for having R assignment (copy & paste completion)
* +15 for having Python assignment (copy & paste completion)
* +10 for having correct file types
* +10 for merging changes to main

# Precept 2 Rubric (Control Flow in R and Python):
* +5 for creating assignment repository
* +10 for creating a draft branch
* +10 for merging with main
* +15 for completing question 1 with accuracy
* +15 for completing question 2 with accuracy
* +15 for completing question 3 with accuracy
* +15 for completing question 4 with accuracy
* +15 for completing question 5 with accuracy
* -5 for each error in questions 1-5

# Precept 3 Rubric (Data IO and String Wrangling):
* +5 for creating assignment repository
* +10 for creating a draft branch
* +10 for merging with main
* +10 for completing question 1 with accuracy
* +10 for completing question 2 with accuracy
* +15 for completing question 3 with accuracy
* +15 for completing question 4 with accuracy
* +15 for completing question 5 with accuracy
* +10 for completing question 6 with accuracy
* -5 for each error in questions 1-6

# Precept 4 Rubric (Data Wrangling):
* +5 for creating assignment repository
* +10 for creating a draft branch
* +10 for merging with main
* +20 for completing question 1 with accuracy
* +15 for completing question 2 with accuracy
* +20 for completing question 3 with accuracy
* +20 for completing question 4 with accuracy
* -5 for each error in questions 1-4

# Precept 5 Rubric (Applying Functions):
* +5 for creating assignment repository
* +10 for creating a draft branch
* +10 for merging with main
* +25 for completing question 1 with accuracy (2 parts)
* +25 for completing question 2 with accuracy (2 parts)
* +25 for completing question 3 with accuracy (2 parts)
* -5 for each error in questions 1-3

# Precept 6 Rubric (Intro to Plotting)
* +5 for creating assignment repository
* +10 for creating a draft branch
* +10 for merging with main
* +15 for completing question 1 in opposite language
* +15 for completing question 1 with accuracy
* +15 for completing question 2 with accuracy
* +15 for completing question 3 with accuracy
* +15 for completing question 4 with accuracy
* -5 for each error in questions 1-4

# Precept 7 Rubric (Plotting from Scratch)
* +5 for creating assignment repository
* +10 for creating a draft branch
* +10 for merging with main
* +25 for completing question 1 with accuracy
* +25 for completing question 2 with accuracy
* +25 for completing question 3 with accuracy
* -5 for each error in questions 1-4

# Precept 8 Rubric (Statistics in Python)
* +5 for creating assignment repository
* +10 for creating a draft branch
* +10 for merging with main
* +25 for completing question 1 with accuracy
* +25 for completing question 2 with accuracy
* +25 for completing question 3 with accuracy
* -5 for each error in questions 1-4